#!/usr/bin/env python3
"""Export the local SQLite database as PostgreSQL SQL for Neon imports."""

from __future__ import annotations

import argparse
import json
import math
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


TABLES = {
    "accidents": [
        ("id", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        ("latitude", "DOUBLE PRECISION NOT NULL"),
        ("longitude", "DOUBLE PRECISION NOT NULL"),
        ("datetime", "TIMESTAMP NOT NULL"),
        ("date", "DATE NOT NULL"),
        ("time", "TIME NOT NULL"),
        ("day_of_week", "VARCHAR(20)"),
        ("hour", "INTEGER"),
        ("weather", "VARCHAR(50)"),
        ("road_type", "VARCHAR(50)"),
        ("severity", "VARCHAR(20)"),
        ("injuries", "INTEGER"),
        ("fatalities", "INTEGER"),
        ("vehicles_involved", "INTEGER"),
        ("description", "TEXT"),
        ("created_at", "TIMESTAMP"),
    ],
    "roads": [
        ("id", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        ("name", "VARCHAR(200) NOT NULL"),
        ("type", "VARCHAR(50)"),
        ("traffic_volume", "INTEGER"),
        ("speed_limit", "INTEGER"),
        ("lanes", "INTEGER"),
        ("latitude", "DOUBLE PRECISION"),
        ("longitude", "DOUBLE PRECISION"),
    ],
    "weather": [
        ("id", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        ("date", "DATE NOT NULL"),
        ("condition", "VARCHAR(50)"),
        ("temperature", "DOUBLE PRECISION"),
        ("humidity", "DOUBLE PRECISION"),
        ("visibility", "DOUBLE PRECISION"),
        ("wind_speed", "DOUBLE PRECISION"),
    ],
    "predictions": [
        ("id", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        ("latitude", "DOUBLE PRECISION NOT NULL"),
        ("longitude", "DOUBLE PRECISION NOT NULL"),
        ("risk_level", "VARCHAR(20) NOT NULL"),
        ("risk_probability", "DOUBLE PRECISION"),
        ("prediction_date", "TIMESTAMP"),
        ("factors", "TEXT"),
    ],
    "users": [
        ("id", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        ("username", "VARCHAR(50) NOT NULL"),
        ("email", "VARCHAR(100) NOT NULL"),
        ("hashed_password", "VARCHAR(200) NOT NULL"),
        ("role", "VARCHAR(20)"),
        ("is_active", "INTEGER"),
        ("created_at", "TIMESTAMP"),
    ],
    "login_audit": [
        ("id", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        ("username", "VARCHAR(50) NOT NULL"),
        ("user_id", "INTEGER"),
        ("ip_address", "VARCHAR(80)"),
        ("user_agent", "TEXT"),
        ("success", "INTEGER"),
        ("failure_reason", "VARCHAR(120)"),
        ("created_at", "TIMESTAMP"),
    ],
}


INDEXES = [
    ("ix_accidents_hour", "accidents", "hour", False),
    ("ix_accidents_severity", "accidents", "severity", False),
    ("ix_accidents_road_type", "accidents", "road_type", False),
    ("ix_accidents_id", "accidents", "id", False),
    ("ix_accidents_longitude", "accidents", "longitude", False),
    ("ix_accidents_datetime", "accidents", "datetime", False),
    ("ix_accidents_weather", "accidents", "weather", False),
    ("ix_accidents_latitude", "accidents", "latitude", False),
    ("ix_roads_type", "roads", "type", False),
    ("ix_roads_id", "roads", "id", False),
    ("ix_weather_id", "weather", "id", False),
    ("ix_weather_date", "weather", "date", False),
    ("ix_predictions_id", "predictions", "id", False),
    ("ix_users_id", "users", "id", False),
    ("ix_users_username", "users", "username", True),
    ("ix_users_email", "users", "email", True),
    ("ix_login_audit_success", "login_audit", "success", False),
    ("ix_login_audit_user_id", "login_audit", "user_id", False),
    ("ix_login_audit_username", "login_audit", "username", False),
    ("ix_login_audit_id", "login_audit", "id", False),
    ("ix_login_audit_created_at", "login_audit", "created_at", False),
]


def quote_identifier(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def copy_value(value: Any) -> str:
    if value is None:
        return r"\N"
    if isinstance(value, float):
        if math.isnan(value):
            return "NaN"
        if math.isinf(value):
            return "Infinity" if value > 0 else "-Infinity"
    text = str(value)
    return (
        text.replace("\\", "\\\\")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def table_exists(connection: sqlite3.Connection, table: str) -> bool:
    row = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    ).fetchone()
    return row is not None


def create_table_sql(table: str, columns: list[tuple[str, str]]) -> str:
    definitions = ",\n    ".join(
        f"{quote_identifier(column)} {column_type}" for column, column_type in columns
    )
    return f"CREATE TABLE {quote_identifier(table)} (\n    {definitions}\n);"


def copy_table(
    connection: sqlite3.Connection,
    output,
    table: str,
    columns: list[tuple[str, str]],
    batch_size: int,
) -> int:
    column_names = [column for column, _ in columns]
    quoted_columns = ", ".join(quote_identifier(column) for column in column_names)
    select_columns = ", ".join(quote_identifier(column) for column in column_names)
    cursor = connection.execute(
        f"SELECT {select_columns} FROM {quote_identifier(table)} ORDER BY id"
    )

    output.write(
        f"COPY {quote_identifier(table)} ({quoted_columns}) FROM stdin WITH (FORMAT text);\n"
    )
    count = 0
    while True:
        rows = cursor.fetchmany(batch_size)
        if not rows:
            break
        for row in rows:
            output.write("\t".join(copy_value(value) for value in row) + "\n")
            count += 1
    output.write("\\.\n\n")
    return count


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export SQLite traffic portal data as a PostgreSQL SQL dump."
    )
    parser.add_argument(
        "--sqlite-db",
        default="traffic_db.db",
        help="Path to the SQLite database, relative to backend/ by default.",
    )
    parser.add_argument(
        "--output",
        default="db_exports/traffic_portal_postgres.sql",
        help="Output SQL path, relative to backend/ by default.",
    )
    parser.add_argument(
        "--exclude-auth",
        action="store_true",
        help="Exclude users and login_audit tables for a public-data-only export.",
    )
    parser.add_argument("--batch-size", type=int, default=5000)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    backend_dir = Path(__file__).resolve().parents[1]
    sqlite_db = Path(args.sqlite_db)
    output_path = Path(args.output)

    if not sqlite_db.is_absolute():
        sqlite_db = backend_dir / sqlite_db
    if not output_path.is_absolute():
        output_path = backend_dir / output_path

    if not sqlite_db.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_db}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    tables = dict(TABLES)
    if args.exclude_auth:
        tables.pop("users", None)
        tables.pop("login_audit", None)

    connection = sqlite3.connect(sqlite_db)
    connection.row_factory = sqlite3.Row
    counts: dict[str, int] = {}

    try:
        missing = [table for table in tables if not table_exists(connection, table)]
        if missing:
            raise SystemExit(f"Missing expected SQLite tables: {', '.join(missing)}")

        with output_path.open("w", encoding="utf-8", newline="\n") as output:
            output.write("-- PostgreSQL export for Traffic Accident Portal.\n")
            output.write(f"-- Source SQLite DB: {sqlite_db}\n")
            output.write(
                f"-- Created: {datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
            )
            output.write("-- Import with: psql \"$DATABASE_URL\" -f this_file.sql\n\n")
            output.write("BEGIN;\n")
            output.write("SET client_encoding = 'UTF8';\n")
            output.write("SET standard_conforming_strings = on;\n\n")

            for table in reversed(tables):
                output.write(f"DROP TABLE IF EXISTS {quote_identifier(table)} CASCADE;\n")
            output.write("\n")

            for table, columns in tables.items():
                output.write(create_table_sql(table, columns) + "\n\n")

            for table, columns in tables.items():
                counts[table] = copy_table(
                    connection, output, table, columns, args.batch_size
                )

            for index_name, table, column, unique in INDEXES:
                if table not in tables:
                    continue
                unique_sql = "UNIQUE " if unique else ""
                output.write(
                    f"CREATE {unique_sql}INDEX {quote_identifier(index_name)} "
                    f"ON {quote_identifier(table)} ({quote_identifier(column)});\n"
                )

            output.write("\n")
            for table in tables:
                sequence = f"{table}_id_seq"
                output.write(
                    "SELECT setval("
                    f"'{quote_identifier(sequence)}', "
                    f"COALESCE((SELECT MAX(id) FROM {quote_identifier(table)}), 1), "
                    f"(SELECT COUNT(*) > 0 FROM {quote_identifier(table)}));\n"
                )

            output.write("\nCOMMIT;\n")

        manifest_path = output_path.with_suffix(".manifest.json")
        manifest = {
            "sqlite_db": str(sqlite_db),
            "postgres_sql": str(output_path),
            "exclude_auth": args.exclude_auth,
            "tables": counts,
            "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        manifest_path.write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        print(f"Created PostgreSQL SQL export: {output_path}")
        print(f"Created manifest: {manifest_path}")
        for table, count in counts.items():
            print(f"{table}: {count}")
    finally:
        connection.close()


if __name__ == "__main__":
    main()
